# Generated by Django 3.2.9 on 2021-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.TextField(max_length=500, verbose_name='Brand')),
                ('Model', models.CharField(max_length=500, verbose_name='Model')),
                ('AccelSec', models.CharField(max_length=200, verbose_name='AccelSec')),
                ('TopSpeed_KmH', models.CharField(max_length=200, verbose_name='TopSpeed_KmH')),
                ('Range_Km', models.CharField(max_length=200, verbose_name='Range_Km')),
                ('Efficiency_WhKm', models.CharField(max_length=250, verbose_name='Efficiency_WhKm')),
                ('FastCharge_KmH', models.CharField(max_length=250, verbose_name='FastCharge_KmH')),
                ('RapidCharge', models.CharField(max_length=255, verbose_name='RapidCharge')),
                ('PowerTrain', models.CharField(max_length=500, null=True, verbose_name='PowerTrain')),
                ('PlugType', models.CharField(max_length=255, verbose_name='PlugType')),
                ('BodyStyle', models.CharField(max_length=255, verbose_name='BodyStyle')),
                ('Segment', models.CharField(max_length=255, verbose_name='Segment')),
                ('Seats', models.CharField(max_length=250, verbose_name='Seats')),
                ('PriceEuro', models.CharField(max_length=500, verbose_name='PriceEuro')),
            ],
        ),
    ]
